/*
 * 
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MyApp.java
 *
 * Created on 5 Feb, 2013, 9:06:40 PM
 */
package sruds;

import java.io.File;
import java.io.IOException;
import java.io.PrintStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JTextArea;

/**
 *
 * @author UDAY
 */
public class MyApp extends javax.swing.JFrame {

    /** Creates new form MyApp */
    JFileChooser jfc = new JFileChooser();
    public MyApp() {
        initComponents();
    }

    private MyApp(String string) {
        super(string);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        queryLabel = new javax.swing.JLabel();
        templateLabel = new javax.swing.JLabel();
        queryField = new javax.swing.JTextField();
        templateField = new javax.swing.JTextField();
        qbrowse = new javax.swing.JButton();
        tbrowse = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        check = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        clear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        queryLabel.setText("         QUERY FILE");
        getContentPane().add(queryLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 150, -1));

        templateLabel.setText("      TEMPLATE FILE");
        getContentPane().add(templateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 150, -1));
        getContentPane().add(queryField, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 170, 160, -1));
        getContentPane().add(templateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 130, 160, -1));

        qbrowse.setText("Browse");
        qbrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qbrowseActionPerformed(evt);
            }
        });
        getContentPane().add(qbrowse, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 170, 80, -1));

        tbrowse.setText("Browse");
        tbrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbrowseActionPerformed(evt);
            }
        });
        getContentPane().add(tbrowse, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 130, 80, -1));

        jLabel1.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 36));
        jLabel1.setText("     Crib Detector");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 530, 80));

        check.setText("Check!!!!!");
        check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkActionPerformed(evt);
            }
        });
        getContentPane().add(check, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 250, -1, -1));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setAutoscrolls(true);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 290, 1360, 110));

        clear.setText("clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 420, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

   private void qbrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qbrowseActionPerformed
       // TODO add your handling code here:
          
        jfc.setDialogTitle("Query File");
          if(jfc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) { 
            File t=jfc.getSelectedFile();
            String a=t.getPath();
            //t.toString();
            
              queryField.setText(a);
            //code to handle choosed file here. 
        } 

       
   }//GEN-LAST:event_qbrowseActionPerformed

   private void tbrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbrowseActionPerformed
       // TODO add your handling code here:
         // JFileChooser jfc = new JFileChooser(); 
        jfc.setDialogTitle("Template File");
          if(jfc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) { 
            //code to handle choosed file here. 
        File t=jfc.getSelectedFile();
            String a=t.getPath();
            //t.toString();
              templateField.setText(a);
          
          } 

   }//GEN-LAST:event_tbrowseActionPerformed

   private void checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkActionPerformed
       // TODO add your handling code here:
        String []argument=new String[2];
        argument[0]=queryField.getText();
        argument[1]=templateField.getText();
        //System.out.println("INSIDE my app"+argument[0]);
        JTextArea textArea = new JTextArea(500, 100);
        
        textArea.setVisible(true);
        
            PrintStream printStream = new PrintStream(new TextAreaOutputStream(jTextArea1));
            System.setOut(printStream);
            //SmithWaterman.main(argument);
        try {
            SmithWaterman.main(argument);
        } catch (IOException ex) {
            Logger.getLogger(MyApp.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(MyApp.class.getName()).log(Level.SEVERE, null, ex);
        }
        

   }//GEN-LAST:event_checkActionPerformed

   private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
      jTextArea1.setText("");
       queryField.setText(null);
       templateField.setText(null);
       // TODO add your handling code here:
   }//GEN-LAST:event_clearActionPerformed
   /* public void settext(String b)
    {
    /*String buffer=new String();
        buffer=Integer.toString(b);    
        //System.out.println(b);
        jTextArea1.append("b");
    }*/
    /**
     * @param args the command line arguments
     */
 
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                MyApp m=new MyApp("Input Files");
                m.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton check;
    private javax.swing.JButton clear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton qbrowse;
    private javax.swing.JTextField queryField;
    private javax.swing.JLabel queryLabel;
    private javax.swing.JButton tbrowse;
    private javax.swing.JTextField templateField;
    private javax.swing.JLabel templateLabel;
    // End of variables declaration//GEN-END:variables
}
